### ISSUE TITLE
is my code good?

### ISSUE THREAD

**Issue by hexmaster111** [Team1091/FRC-2016-Stronghold#1]
nobody knows, can you check?

**Comment by brckelly** [comment]
Sorry I have not been able to spend as much time with the team as I would have hoped. I was planning on stopping by tonight and I can help go over the code.

**Comment by stewsters** [comment]
It looks like you have some {} messed up.  You want to have a closing bracket after
 moveToDeg = (moveToDeg + 1);

Also, you have a check to see if the yAxis is greater than 0.3, then have another to check if yAxis is greater than -0.3, which it will always be if it was greater than 0.3.  The net effect is that you will be able to move down, but not up.

I think you want to change the second check to see if the yAxis is less than -0.3.

[edit]  Also make sure you run that auto-formatter before you commit code, it will make bracket issues really obvious
